project:
  type: website
  output-dir: docs
website:
  site-url: https://sayalaruano.github.io/
  favicon: images/a_asarlogo.ico
  google-analytics: 
    tracking-id: "UA-212436276-1"
    anonymize-ip: true
  navbar:
    title: false
    logo: https://raw.githubusercontent.com/sayalaruano/sayalaruano.github.io/HEAD/images/asar_logo.svg
    right:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: https://sayalaruano.github.io/cv/
        text: CV
      #- icon: github
      #  href: https://github.com/
  page-footer: 
    background: light
    left: © Copyright 2026, Sebastian Ayala Ruano
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/sayalaruano/sayalaruano.github.io){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}
format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true



