---
title: "About"
subtitle: "A bit more about me, both inside and outside of my job"
title-block-banner: true
---

## {{< fa laptop-code title="A laptop" >}} Professionally

I am a MSc student in [Systems Biology](https://www.maastrichtuniversity.nl/education/master/systems-biology) at [Maastricht University](https://www.maastrichtuniversity.nl/nl), the Netherlands. Previously, I worked as a research assistant and data science consultant at different institutes. In my last job, I developed a method based on network science and similarity searching to explore the **chemical space of antiparasitic peptides** and discover new potential drugs, which was recently published in this [article](https://pubs.acs.org/doi/10.1021/acsomega.2c03398).

I completed my bachelor's degree in **Biotechnology Engineering** as a major, and **Software Engineering** as a minor at Universidad San Francisco de Quito (USFQ) in Ecuador. During my studies, I discovered that **Bioinformatics** is the field that captured my interest in research because it merged both of my background areas. To pursue these interests, I worked in various laboratories at USFQ such as the [Computational and Theoretical Chemistry Group](https://www.usfq.edu.ec/en/research/grupo-de-quimica-computacional-y-teorica), the **Applied Signal Processing and Machine Learning Group**, and the **Grupo de Medicina Molecular y Traslacional**; and research centers from institutions inside and outside of my country, including the [Bio-Chemoinformatics Group](https://bioquimio.udla.edu.ec/) at Universidad de Las Américas in Ecuador and the [Tumor Metabolism and Therapeutic Oncology Laboratory](https://life.gist.ac.kr/tmtor/) at Gwangju Institute of Science and Technology in South Korea.

I have been part of some initiatives to boost Bioinformatics in Ecuador through the creation of the first Regional Student Group from the International Society for Computational Biology Student Council in my country. Also, I am participating in some regional projects with people from different countries of Latin America. 

Throughout the last year, I joined some open science and software development communities, including the [Open Life Science](https://openlifesci.org/) and the [Streamlit Creators](https://streamlit.io/creators). In addition, I completed [The Carpentries](https://carpentries.org/) instructor training program, and I hope to teach my first course/lesson this year. 

<br>

## {{< fa hiking title="A person with a backpack and trekking pole" >}} Personally

When I am not working, I can be found riding my mountain bike, hiking, listening to music, watching thrillers or documentary films, or reading books about science communication, mystery, or history.

<br>
