---
title: "Publications"
title-block-banner: true
---

## Peer reviewed journal articles
- Aguilera-Mendoza, L., **Ayala-Ruano, S.**<sup>^</sup>, Martinez-Rios, F., Chavez, E., García-Jacas, C. R., Brizuela, C. A., & Marrero-Ponce, Y. (2023). **StarPep Toolbox: an open-source software to assist chemical space analysis of bioactive peptides and their functions using complex networks**. *Bioinformatics*, 39 (8), btad506. doi: [doi.org/10.1093/bioinformatics/btad506](https://doi.org/10.1093/bioinformatics/btad506)

- **Ayala-Ruano S.**, Marrero-Ponce Y., Aguilera‑Mendoza L., Pérez N., et al. (2022). **Exploring the Chemical Space of Antiparasitic Peptides and Discovery of New Promising Leads through a Novel Approach based on Network Science and Similarity Searching**. *ACS omega*. doi: [doi.org/10.1021/acsomega.2c03398](https://doi.org/10.1021/acsomega.2c03398).

  - Preprint: [doi.org/10.26434/chemrxiv-2021-tgv69-v2](https://doi.org/10.26434/chemrxiv-2021-tgv69-v2).

- Oña-Chuquimarca, S., **Ayala-Ruano, S.**, Goossens, Pauwels, L., et al. (2020). **The molecular basis of JAZ-MYC coupling, a protein-protein interface essential for plant response to stressors**. *Frontiers in Plant Science*, 11, 1139. doi: [10.3389/fpls.2020.01139
](https://doi.org/10.3389/fpls.2020.01139). 

  - This article was chosen to feature in the Frontiers in Plant Science 2020 highlights e-book collection. doi: [10.3389/978-2-88966-723-9](https://doi.org/10.3389/978-2-88966-723-9)

- **Ayala‐Ruano, S.**, Santander‐Gordón, D., Tejera, E., Perez‐Castillo, Y., & Armijos-Jaramillo, V. (2019). **A putative antimicrobial peptide from Hymenoptera in the megaplasmid pSCL4 of Streptomyces clavuligerus ATCC 27064 reveals a singular case of horizontal gene transfer with potential applications**. *Ecology and Evolution*, 9 (5), 2602-2614. doi: [10.1002/ece3.4924](https://doi.org/10.1002/ece3.4924).

<br>

## Editorial journal articles
-  Osorio-Mogollon C, Grentzinger V, Olguin-Orellana GJ, **Ayala-Ruano S.**, et al. (2023). **ISCB Student Council Symposium 2021, a virtual global venue: challenges and lessons learned**. *F1000Research*, 12(50). doi: [10.12688/f1000research.129945.1](https://doi.org/10.12688/f1000research.129945.1) 

- **Ayala-Ruano S.**<sup>^</sup>, Hernandez, F., Ortega, A., Infante, D., et al. (2022). **Highlights of the 1st Ecuadorian-Venezuelan Symposium of Young Researchers in Bioinformatics (1SEVJIB)**. *F1000Research*, 11(1086), 1086. doi: [10.12688/f1000research.125381.1](https://f1000research.com/articles/11-1086/v1).

- Castillo-Vilcahuaman, C., Valdivia C., Osorio-Mogollón C., Silva-Andrade, C., Puche, R., **Ayala‐Ruano, S.**, et al. (2020). **4th ISCB Latin American Student Council Symposium: a virtual  and inclusive experience during COVID19 times**. *F1000Research*, 9.  doi: [10.12688/f1000research.28330.1](https://f1000research.com/articles/9-1460/v1).

<br>

## Others
- **Ayala-Ruano, S.**<sup>^</sup>, & Zurita, J. (2021). **HerrCompBioinfo: un recurso educativo de código abierto de herramientas computacionales para entusiastas de la Bioinformática**. doi: [doi.org/10.5281/zenodo.5748335](https://doi.org/10.5281/zenodo.5748335)

^co-first author